services:
  postgres:
    image: postgres:latest
    container_name: contacts-db
    restart: always
    environment:
      POSTGRES_DB: contacts_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: contacts-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8083:80" # <- Aqui mapeia a porta externa 8083 para a interna 80. Pode utilizar a 8081, é que a minha estava ocupada e não queria pausar o container
    depends_on:
      - postgres

volumes:
  pgdata:


